version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - '33600:3306'
    environment:
      MYSQL_DATABASE: task-management
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local